services:
  fpm:
    image: php82:v1
    container_name: bgd_app
    volumes:
      - /Volumes/work/code/php/bgd-erp/web:/var/www/erp
      - /Volumes/work/code/php/mes:/var/www/mes
    working_dir: /var/www/erp
    networks:
      - docker-utils-network

  nginx:
    image: nginx:stable-alpine
    container_name: bgd_erp_nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9011:80"
      - "9012:9012"
    volumes:
      - /Volumes/work/code/php/bgd-erp/web:/var/www/erp
      - /Volumes/work/code/php/mes:/var/www/mes
      - ./conf:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - fpm
    networks:
      - docker-utils-network
networks:
  docker-utils-network:
    external: true