services:
  laravel_app:
    image: php83:v2
    container_name: laravel_app
    volumes:
      - /Volumes/work/code/php/laravel:/var/www
    working_dir: /var/www
    networks:
      - docker-utils-network

  web:
    image: nginx:stable-alpine
    container_name: laravel_web
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8085:80"
    volumes:
      - /Volumes/work/code/php/laravel:/var/www
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - laravel_app
    networks:
      - docker-utils-network

networks:
  docker-utils-network:
    external: true