services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD='.5MeyxKp#q;:I'60v7J?=9m2/'
    command: ["redis-server", "--requirepass", ".5MeyxKp#q;:I'60v7J?=9m2/"]
    networks:
      - docker-utils-network
networks:
  docker-utils-network:
    external: true